---
title: "OpenHDF5"
author: "Michiel P. Veldhuis"
date: "20 juni 2016"
output: html_document
---

```{r loadlibraries}
# load libraries
library(raster)
library(rhdf5)
library(rgdal)

```

## Let's Open A File
```{r select-file}
# define file location (for DRY)
f <- "../NEONdata/D17-California/TEAK/2013/spectrometer/reflectance/Subset3NIS1_20130614_100459_atmcor.h5"

# view h5 structure
h5ls(f)

```


## Import Spatial Information
```{r import-spatial-info}
# import spatial info
mapInfo <- h5read(file = f, 
                  name = "map info",
                  read.attributes = TRUE)
mapInfo


```



## Grab Reflectance Metadata
```{r get-refl-metadata}

# read in reflectance data attributes
reflInfo <- h5readAttributes(file = f,
                             name = "Reflectance")
reflInfo

# define scale factor
scaleFactor <- reflInfo$`Scale Factor`
str(scaleFactor)

# define no data value
noDataValue <- as.numeric(reflInfo$`data ignore value`)
str(noDataValue)
```


## Import Data Dims
```{r import-dims}
# open file for viewing
fid <- H5Fopen(f)
str(fid)
# open / connect to the reflectance dataset
did <- H5Dopen(fid, "Reflectance")
did
# grab the dataset dimensions
sid <- H5Dget_space(did)
dims <- H5Sget_simple_extent_dims(sid)$size
dims

# close all open connections
H5Sclose(sid)
H5Dclose(did)
H5Fclose(fid)

```


## Read In Reflectance
```{r read-data}

# extract slice of H5 file
b56 <- h5read(file = f,
              name = "Reflectance",
              index = list(1:dims[1], 1:dims[2], 56)
              )
b56
              


```

## Convert Data to Matrix
```{r convert-matrix}
# convert to matrix
b56 <- b56[,,1]

# let's plot some data
image(b56)
image(log(b56),
      main="log transformed data")

hist(b56)

```

## Time to Clean Up Our Data

```{r data-clean-up}

# assign no data values to object
b56[b56 == noDataValue] <- NA

# apply scale factor
b56 <- b56 / scaleFactor
hist(b56)

```

## Transpose Data
```{r transposedata}
# transpose the data
b56 <- t(b56)
image(log(b56))

```

## Create Spatial Extent
```{r create-spatial-extent}

# split out Map Info object
mapInfo <- unlist(strsplit(mapInfo, ","))

# value at 3 element in list
xMin <- as.numeric(mapInfo[4])
yMax <- as.numeric(mapInfo[5])


# get spatial resolution
xres <- as.numeric(mapInfo[6])
yres <- as.numeric(mapInfo[7])

# calculate Xmax and Ymin
xMax <- xMin + (dims[1] * xres)
yMin <- yMax - (dims[2] * yres)

```


## Create spatial extent
```{r create-extent}
rasExt <- extent(xMin, xMax,
                 yMin, yMax)
rasExt

# create raster object
b56r <- raster(b56,
               crs=CRS("+init=epsg:32611"))

extent(b56r) <- rasExt
b56r
plot(b56r,
     main="spatially referenced data")
```


# Import NEON Functions
```{r import-using-functions}
library(devtools)

install_github("lwasser/neon-aop-package/neonAOP")
library(neonAOP)

b55 <- open_band(f, 55, epsg=32611)
b55
plot(b55)

# import several bands
bands <- c(58, 34, 19)

# define epsg
epsg <- 32611

# create raster stack
RGBstack <- create_stack(file = f, 
                         bands=bands, 
                         epsg = epsg)

RGBstack
plotRGB(RGBstack, 
        stretch='lin')

# cir image
bandscir <- c(90, 34, 19)
CIRstack <- create_stack(file = f, 
                         bands=bandscir, 
                         epsg = epsg)

plotRGB(CIRstack,
        stretch='lin')
```

Check
